### ISSUE TITLE
The lookup table 'incidents' does not exist.

### ISSUE THREAD

**Issue by kurtzonico** [simcen/alert_manager#111]
HI,

After a fresh install of the Alert Manager App when i open the App i receive this error:

_"Error in 'lookup' command: The lookup table 'incidents' does not exist."_
![image](https://cloud.githubusercontent.com/assets/17025362/12749871/9608fc3c-c9b3-11e5-994d-233e4899c0ec.png)

and if i go to the Settings->Incident Settings i also get this error:

_ Error in 'inputlookup' command: The lookup table 'External command based lookup 'incident_settings' is not available because KV Store initialization has failed. Please contact your system administrator.' is invalid. _
![image](https://cloud.githubusercontent.com/assets/17025362/12749909/cb3d3972-c9b3-11e5-84ca-bde2c206d492.png)

Can any one already experience this issue, and who to resolve it.

Many Thanks in advance.

**Comment by JohnySJO** [comment]
I have the same problem. It looks like there is a problem with the KV Store in an distributed deployment.
I could find the following errors in the log:
04-18-2016 18:06:12.506 ERROR KVStoreLookup - External command based lookup 'incidents' is not available because KV Store initialization has failed. Please contact your system administrator.
04-18-2016 18:06:12.506 ERROR KVStoreLookup - Failed to execute KV Store lookups: External command based lookup 'incidents' is not available because KV Store initialization has failed. Please contact your system administrator.
04-18-2016 18:06:12.506 ERROR KVStoreLookup - Failed to create lookup context
04-18-2016 18:06:12.507 ERROR LookupOperator - Error in 'lookup' command: The lookup table 'incidents' does not exist or is not available.

**Comment by simcen** [comment]
Hi guys
It looks like this is a generic Splunk issue rather than a bug in our app.
Could you check for invalid certificates by running these commands:
`cd /opt/splunk/etc/auth/
for i in *.pem; do echo $i && openssl x509 -in $i -text | grep -A 2 Validity ; done`

_Not after_ needs to be in the future. If there are outdatet certificates, you can recreate them by running
`/opt/splunk/bin/splunk createssl server-cert -d . -n server`
After, restart Splunk.
More details:
https://answers.splunk.com/answers/314499/after-upgrading-to-splunk-630-why-am-i-getting-the.html

Let me know if this helps.
Simon

**Comment by simcen** [comment]
Do you have any feedback on this?

**Comment by JohnySJO** [comment]
Hi,

you are right. It was something with the mongodb with certificates in splunk.
After recreating the certifiacates and restarting, it worked as designed.

Regards
Johann

**Comment by simcen** [comment]
Ok great. thanks for the feedback
