### ISSUE TITLE
Pagination in Incident Posture is broken in Splunk 6.5

### ISSUE THREAD

**Issue by lkm** [simcen/alert_manager#154]
I'm only seeing a Prev and Next button, if I click next table completely disappears. I assume something must've changed in one of the built-in javascript libs.

![screen shot 2016-10-18 at 15 07 49](https://cloud.githubusercontent.com/assets/1745971/19481109/c0a86bdc-9544-11e6-9aed-b500c2ff8c9f.png)

**Comment by simcen** [comment]
Thx for the report. I can confirm this issue and will provide a solution asap

**Comment by lkm** [comment]
Cheers @simcen!

**Comment by simcen** [comment]
Fixed in 77670a9230d7972ab7b15eff7284f1380fc87d08.
@lkm Two options:
1. Quick workaround: Comment line 313 in appserver/static/incident_posture.js (you'll loose the option to configure the number of incidents shown in a table before Splunk starts to paginate):
`//obj.settings.set({ pageSize: settings.entry.content.get('incident_list_length') });`
2. Apply patch:
https://gist.github.com/simcen/2bc98bcce54d0599f8d336868301273f

Let me know if this helps.

**Comment by lkm** [comment]
Great stuff @simcen, applied the patch and it took care of it. Thank you for the incredibly quick response!

**Comment by simcen** [comment]
Welcome and thanks for the feedback
