### ISSUE TITLE
Alert Truncation issue 

### ISSUE THREAD

**Issue by moshekaplan** [simcen/alert_manager#162]
If an alert's events have a large amount of data, the Alert Manager will truncate the displayed result.

This can be fixed by adding the following lines to the props.conf in the TA-alert_manager Splunk APP:

File: `/opt/splunk/etc/apps/TA-alert_manager/local/props.conf`

```
[alert_metadata]
TRUNCATE=0

[alert_results]
TRUNCATE=0
```

**Comment by simcen** [comment]
Thx for the report. Please don't set TRUNCATE to 0, this has very bad implications to the indexing performance in Splunk. Just set it to an arbitrary high number.
This has been fixed in the latest version uploaded to the Splunkbase (v2.1.1, https://splunkbase.splunk.com/app/3365/) where I set 
`TRUNCATE = 104857600`
