### ISSUE TITLE
Errors in deploying the app in distributed environment

### ISSUE THREAD

**Issue by juho-nurmi** [simcen/alert_manager#171]
Hi,

We are having a problems in deploying the App to clustered indexers from Cluster Master(s).
We are getting the following errors:
<hostname>: Invalid key in stanza [alert_manager] in /opt/splunk/etc/master-apps/alert_manager/default/alert_actions.conf, line 9: param.auto_assign_owner (value: unassigned).

<hostname>: Invalid key in stanza [alert_manager] in /opt/splunk/etc/master-apps/alert_manager/default/alert_actions.conf, line 10: param.impact (value: low).

<hostname>: Invalid key in stanza [alert_manager] in /opt/splunk/etc/master-apps/alert_manager/default/alert_actions.conf, line 11: param.urgency (value: low).

<hostname>:No spec file for: /opt/splunk/etc/master-apps/alert_manager/default/alert_manager.conf 

I haven't had the time properly to test the app, but seems to work (we see alerts in the dashboard) , when we force it to be deployed with (splunk apply cluster-bundle --skip-validation) command. Additionally, with the command "splunk btool check --debug" we don't see any problems with the files related to this app, which is strange..

The installation of the App to a single search head went fine from the webgui (no errors mentioned anywhere). Also, no problems encountered with the add-on installations, in distributed environment and in the single search head.

**Comment by johnfromthefuture** [comment]
I'd have to dig into it more but unless you are running search heads on your indexer cluster (not recommended), you do not need to deploy the alert manager app to indexers. There is a TA-alert_manager app that gets deployed for props/transforms/indexes.

**Comment by johnfromthefuture** [comment]
I looked into it more and everything appears to check out. The alert_actions.conf.spec contains the settings defined in alert_actions.conf. I've deployed the app in a distributed environment and on a standalone box without issue. I have not attempted to push the full alert_manager app to an indexer cluster - since it's an unnecessary action, I can't shove that into my prod environment.

Anyway, while there may be some odd compatibility issue between the full app and indexer clusters, I can confirm that it does not impact my ability to generate/review/triage alerting. I'm going to close out this issue with no action taken. 

Thanks again.
