### ISSUE TITLE
Auto Close the Expired incidents not working

### ISSUE THREAD

**Issue by AlexPalanisamySoundariya** [simcen/alert_manager#176]
Hello Team,

I have alert which will run every 1 minute to check the windows service is running or not. 
(using **winhostmon**)
(Timerange as -1m earlier)

I have checked the Auto-Close expired incidents and  **Auto-resolve previously opened identical incidents** option in order to suppress the duplicates in my alert. 

The expiration time is set to 1 minute. Now, it should close the new incidents which is created before 1 minute. But it is not closing.

Please advise. 

Thank you!

**Comment by johnfromthefuture** [comment]
The expiration time isn't something that's easily set and defaults to 86400 (24 hours) so that may be the issue you are experiencing here. This value comes from savedsearches.conf and is passed as part of the alert metadata:

```dispatch.ttl = <integer>[p]
* Indicates the time to live (in seconds) for the artifacts of the scheduled
  search, if no actions are triggered.
* If the integer is followed by the letter 'p' Splunk interprets the ttl as a
  multiple of the scheduled search's execution period (e.g. if the search is
  scheduled to run hourly and ttl is set to 2p the ttl of the artifacts will be
  set to 2 hours).
* If an action is triggered Splunk changes the ttl to that action's ttl. If
  multiple actions are triggered, Splunk applies the largest action ttl to the
  artifacts. To set the action's ttl, refer to alert_actions.conf.spec.
* For more info on search's ttl please see limits.conf.spec [search] ttl
* Defaults to 2p (that is, 2 x the period of the scheduled search).```

The auto-previous resolve option is done based on the alert title only so if you use any token substitution in the title, this would result in a new incident not resolving the previous incident. 

I would check both of these and report back if neither is the case for you. If you need additional assistance, please let me know more about the search you are using and the version of Alert Manager you are on.

Aside from that, I can tell you that the auto-resolve options can be impacted by the app's ability to successfully query the KV store via the rest API. Auto-resolving previous events, for example, requires one query to pull a list of events based on alert title and status. Then, for each incident retrieved, it needs to send another query to update the status. It shouldn't be an issue but something worth knowing. Though, this process may have issues depending on the alert title being used - certain characters could cause queries to fail as I'm not seeing any escaping of the input data based on a quick look at the code.

**Comment by AlexPalanisamySoundariya** [comment]
Thank you very much John!

My expectation is simple. 
1. I'm executing the below saved search every 1 minute. (Earliest -1m)
**index=test source="WMI:Services"  Name=service  "StartMode=Auto"   State!="Running"**
2. If the result is positive and for each result, it should trigger an alert. 
3. Throttle enabled. It will not trigger alert for next 1 hour.

Now, Actions,
In Alert manager app, I enabled only
1. Auto-resolve expired incidents &
2. Auto-resolve previously opened identical incidents

Under **Searches, reports, and alerts**, My Alert Name
Expiration time is set to 1 hour. (which means the alert will expire in 60 minutes) Right??

What I'm expecting is
It should close the triggered alert every one hour.
At the same time, if the search result is positive, on the next run, it will create a new alert. 
In case, if the issue is resolved, the expired alert will be closed automatically. And no new alerts will trigger anymore.

So, there will be no need of manual attention to the already resolved issues.

But, I'm failed to get the result.  Is there anything that I have to do apart from this configuration. 

Please advise.

Thank you!

**Comment by AlexPalanisamySoundariya** [comment]
Thank you very much John!
