### ISSUE TITLE
Suppress Email Notifications

### ISSUE THREAD

**Issue by jdeer0618** [simcen/alert_manager#178]
I might be missing this but is there a way to suppress the "Incident created" email notification if the incident is auto resolved?

Basically, I have a search that runs every 15 mins looking for critical log sources that have stopped indexing data. One of the sources has been down for nearly three days and we get an "Incident Created" notification every 15 minutes for that source. Needless to say, all the email notifications is annoying so I'd like for emails to be suppressed for this alert as well.

Thanks!
JD

**Comment by johnfromthefuture** [comment]
So I wanted to dig into this a bit because this is a portion of AlertManager that I'm not using today. Let me walk through what I'm seeing.

In alert_manager.py, we have `eh = EventHandler(sessionKey=sessionKey)` which sets up the event handler. (The notification handler setup is nested inside the event handler. Took me a minute to see that one.) In the dev branch, around line 501, we have this:
```if incident_suppressed == False:
            log.info("Firing incident_created event for incident=%s" % incident_id)
            eh.handleEvent(alert=search_name, event="incident_created", incident={"owner": settings.get('default_owner')}, context=ic.getContext())
        else:
            log.info("Firing incident_suppressed event for incident=%s" % incident_id)
            eh.handleEvent(alert=search_name, event="incident_suppressed", incident={"owner": settings.get('default_owner')}, context=ic.getContext())```

And this is where the incident created event is coming from. Today, the logic seems to only check if an incident is suppressed and, really, that's only to determine which event to fire off. And here's where I have to make an assumption on your part.

There are 2 options in this dev branch for auto-resolution. One will automatically resolve previous incidents while the other resolves new 'duplicate' incidents. Around line 531 is where the auto duplicate resolution happens:

```elif config['auto_subsequent_resolve'] and incident_suppressed == False:
            log.debug("auto_subsequent_resolve is active for %s. Starting to handle it." % search_name)
            setIncidentAutoSubsequentResolved(ic, settings.get('index'), sessionKey)```

This is the one that I think you care about. I think this can be accomplished by making a few minor changes which are largely organizational. I moved the duplicate checking process up and then had it return a true/false if an event is considered duplicate/or not. The result of that is used to determine if an "incident created" notification needs to be fired. I'll check it in after I validate alert_manager.py continues to function afterwards.

**Comment by johnfromthefuture** [comment]
Did this fix your issue as expected?

**Comment by jacobappleton** [comment]
I was having the same issue. I pulled down the latest version of the code, built it and installed in on my test Splunk server and it appears to now be working as I expected.

One thing that doesn't seem to work though, is the auto-resolve feature of the alerts.

In the [docs](http://docs.alertmanager.info/en/latest/user_manual/) it says:

> **Auto-resolve expired incidents**
> To use the "Auto-resolve expired incidents" feature, the expiration time of the triggered alert time should be set. E.g. if an alert search runs every 15 Minutes, the expiration time should also be set to 15 Minutes.

I can't see any expiration time settings anywhere. Am I missing something?

**Comment by johnfromthefuture** [comment]
The setting you mention is unrelated to this thread so we should put it elsewhere; the issue you note isn't a bug, necessarily. It's more like a needed enhancement.

So in savedsearches.conf, you can set the option "dispatch.ttl" and this appears to be where alert manager gets the time to live value. So if you wanted an alert to expire after 15 minutes, for example, you'd want to set the dispatch.ttl in savedsearches.conf to 900.

This isn't necessarily a great solution because most people are probably working solely inside the web GUI where that setting isn't readily available. It may be best to create a configuration item along with the other alert manager configs. That should be a separate enhancement request.

**Comment by johnfromthefuture** [comment]
The original request seems to have been solved. I've added #193 to address the second issue noted here.
