### ISSUE TITLE
Loading history table under incident drill-down is taking long time.

### ISSUE THREAD

**Issue by JigarLad** [simcen/alert_manager#179]
While we drill-down to check incident history, the time it takes to represent history table is very long. Cant event see how it fetches the history table. 
![incident drill down](https://cloud.githubusercontent.com/assets/4306403/26446018/05935a46-4160-11e7-9779-8f29a56c88ca.PNG)

**Comment by johnfromthefuture** [comment]
There's a macro that controls that, should be the `incident_history(1)` macro:

`eventtype=incident_change incident_id="$incident_id$" | sort - _time | eval previous_value=coalesce(previous_status, previous_owner, previous_urgency) | eval attribute=case(isnotnull(owner),"owner",isnotnull(urgency),"urgency",isnotnull(status),"status") | eval attribute_val=case(isnotnull(owner),owner,isnotnull(urgency),urgency,isnotnull(status),status) | eval suppression_rules=if(isnotnull(suppression_rule),mvjoin(suppression_rule,", "),"") | eval details=case(action="auto_previous_resolve","Incident resolved by system (because of a new incident)",action="auto_ttl_resolve","Incident resolved by system (TTL reached)",action="create","Incident created",action="change",attribute + " has been changed from '" + previous_value + "' to '" + attribute_val+"'", action="suppress", "Incident suppressed by rules: " + suppression_rule, action="auto_suppress_resolve", "Incident auto-suppressed by rules: " + suppression_rule, action="comment", "Comment added", action="new_subsequent_incident", "New identical incident with incident_id='"+ new_incident_id +"' has been created and automatically resolved.", action="auto_subsequent_resolve", "Incident resolved by system (because of a identical pre-existing incident)") | table _time, user, action, details, comment`

**Comment by JigarLad** [comment]
@johnfromthefuture I have figured out this marco before also. Will it be fine to modify this query? Or is there any way to reduce to response time. I can simply get history using below query:
index=alerts incident_id="$incident_id$" | table _time,user,action,details,comment

**Comment by johnfromthefuture** [comment]
You can modify the macro however you see fit to produce results that meet your requirements. If you are experiencing issues with response time of the search, though, this likely has more to do with underlying architecture of your splunk system. Swapping out the search will effectively remove a number of evals but I would not expect this to improve performance in any meaningful way.

All I can suggest is to give it a try and see if it works for you.

**Comment by JigarLad** [comment]
Well sorted! Replaced the eval query with the simple one I mentioned. Within click incident history is now loading.
